# packages to install
install.packages('tidyverse')
install.packages('lubridate')
install.packages('ggpubr')
install.packages('cowplot')
install.packages('zoo')
install.packages('here')
install.packages('remotes')
remotes::install_github('aemon-j/gotmtools', ref = 'yaml')
remotes::install_github('FLARE-forecast/LakeEnsemblR')
install.packages('rLakeAnalyzer')
